/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--color-muted-foreground) / <alpha-value>)',
        'subtle-foreground': 'rgb(var(--color-subtle-foreground) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        ink: '#121510',
        canvas: 'rgb(var(--color-canvas) / <alpha-value>)',
        paper: 'rgb(var(--color-paper) / <alpha-value>)',
        intelligence: '#4E6817',
        'intelligence-dark': '#35490B',
        'intelligence-soft': 'rgb(var(--color-intelligence-soft) / <alpha-value>)',
        'secondary-fill': 'rgb(var(--color-secondary-fill) / <alpha-value>)',
        success: '#39734B',
        'success-soft': 'rgb(var(--color-success-soft) / <alpha-value>)',
        urgent: '#B94A42',
        'urgent-soft': 'rgb(var(--color-urgent-soft) / <alpha-value>)',
        warning: '#96601D',
        'warning-soft': 'rgb(var(--color-warning-soft) / <alpha-value>)',
        scheduled: '#4E6884',
        'scheduled-soft': 'rgb(var(--color-scheduled-soft) / <alpha-value>)',
        completed: '#4A7358',
        'completed-soft': 'rgb(var(--color-completed-soft) / <alpha-value>)',
        taupe: 'rgb(var(--color-taupe) / <alpha-value>)',
        'muted-ink': '#5C6257',
        'subtle-ink': '#7D8478',
        'kast-lime': '#B8F34A',
        'auth-canvas': 'rgb(var(--color-auth-canvas) / <alpha-value>)',
        'auth-hero': '#121510',
        'auth-surface': 'rgb(var(--color-auth-surface) / <alpha-value>)',
        'auth-line': 'rgb(var(--color-auth-line) / <alpha-value>)',
        'auth-ink': 'rgb(var(--color-auth-ink) / <alpha-value>)',
        'auth-muted': 'rgb(var(--color-auth-muted) / <alpha-value>)',
        'auth-on-dark': '#F7F8F4',
        'auth-on-dark-muted': '#ADB3A8',
        'auth-accent': '#B8F34A',
        'auth-accent-ink': '#121510',
      },
      fontFamily: {
        sans: ['Inter_400Regular'],
        inter: ['Inter_400Regular'],
        'inter-medium': ['Inter_500Medium'],
        'inter-semibold': ['Inter_600SemiBold'],
        'inter-bold': ['Inter_700Bold'],
        display: ['SpaceGrotesk_500Medium'],
        'display-semibold': ['SpaceGrotesk_600SemiBold'],
        'display-bold': ['SpaceGrotesk_700Bold'],
      },
    },
  },
  plugins: [],
};
